# Generated by Django 4.0.3 on 2022-03-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('YS', '역삼'), ('DG', '도곡'), ('AGJ', '압구정'), ('MD', '목동'), ('JG', '종각')], max_length=3)),
                ('name', models.CharField(max_length=15)),
                ('price', models.PositiveIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
