# Generated by Django 4.0.3 on 2022-03-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='휴대폰 번호')),
                ('created_d', models.DateField(auto_now_add=True, verbose_name='등록 날짜')),
                ('modified_d', models.DateField(auto_now=True, verbose_name='정보 변경 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='크레딧(원)')),
                ('valid_date', models.DateField(null=True, verbose_name='사용 가능 기간')),
                ('created_d', models.DateField(auto_now_add=True, verbose_name='생성 날짜')),
                ('modified_d', models.DateField(auto_now=True, verbose_name='수정 날짜')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.customer', verbose_name='고객')),
            ],
        ),
    ]
