# Generated by Django 4.0.3 on 2022-03-22 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='크레딧(원)')),
                ('valid_date', models.DateField(null=True, verbose_name='사용 가능 기간')),
                ('created_d', models.DateField(auto_now_add=True, verbose_name='생성 날짜')),
                ('modified_d', models.DateField(auto_now=True, verbose_name='수정 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
    ]
