# Generated by Django 4.0.3 on 2022-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='created_dt',
            new_name='created_d',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='modified_dt',
            new_name='modified_d',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='created_dt',
            new_name='created_d',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='modified_dt',
            new_name='modified_d',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='휴대폰 번호'),
        ),
    ]
