# Generated by Django 4.0.3 on 2022-03-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', '결제 완료'), ('RTP', '결제 대기'), ('RF', '환불 완료')], default='RTP', max_length=3, verbose_name='결제 상태')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='예약 생성 시각')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='예약 상태 변경 시각')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.customer', verbose_name='회원 휴대폰 번호')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.program', verbose_name='수업 번호')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='결제 금액')),
                ('refund_rate', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True, verbose_name='환불 정책률')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='결제 시각')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='결제 정보 변경 시각')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='예약 번호')),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypage.credit', verbose_name='사용된 크레딧 번호')),
            ],
        ),
    ]
